### ISSUE TITLE
publish for Scala 2.13.0

### ISSUE THREAD

**Issue by SethTisue** [typelevel/paiges#152]
my immediate interest is actually to have a branch I could use in the Scala 2.13 community build

(but publishing probably could happen at the same time)

**Comment by SethTisue** [comment]
depends on https://github.com/typelevel/cats/issues/2853

perhaps to make this easier, the catalysts dependency could be dropped?

```
cats/src/test/scala/org/typelevel/paiges/LawTests.scala:import catalysts.Platform
cats/src/test/scala/org/typelevel/paiges/LawTests.scala:import catalysts.macros.TypeTagM // need this import for implicit macros
```

**Comment by johnynek** [comment]
yeah, dropping catalysts would be fine.

We can copy and paste this:

https://github.com/typelevel/algebra/pull/228/files#diff-13043dc215ab18d95b0cbbecc5073f57

It's a shame we don't have something like that in the standard library. It seems like basically everyone doing cross platform work needs it.

**Comment by SethTisue** [comment]
@sjrd is there something we ought to add to stdlib for this?

**Comment by sjrd** [comment]
Putting something like that in the stdlib is tricky, because when compiling a Scala.js library/app, it is compiled against the .class files and symbol table of the JVM scala-library.jar, but then linked against the JS one. That means that a constant-expression `final val` must necessarily have the same value on both platforms. If the JVM stdlib defines `final val isJVM = true`, Scala.js cannot actually override that with `final val isJVM = false`, even by replacing the source file.

Now, I believe most libraries would use this `isJVM/isJS` thing and define them as `final val`s actually need them to be constant-expressions, for entire `if` branch to be dropped by scalac, before linking tries to reach stuff that only exists on the JVM. If not, then every library could just trivially define their own
```scala
val isJS = 1.0.toString == "1"
val isJVM = !isJS
```
and be done with it.

So no, I don't think there's anything that can be added to the stdlib for this, unfortunately.

**Comment by larsrh** [comment]
2.13.0 is out.

**Comment by SethTisue** [comment]
("I would like cats to release a final version before publishing a version", says @johnynek over at #160)

**Comment by jdrphillips** [comment]
Cats uses sbt-microsite, which uses scalameta mdoc, which is blocked by metaconfig, which is blocked by paiges!

**Comment by johnynek** [comment]
Well then. I guess we need to go first. Circular dependencies are the worst.

**Comment by larsrh** [comment]
OK, I will try to make this release happen.

**Comment by larsrh** [comment]
OK, `v0.2.3` was botched because of changes in Travis CI setup. I'll try again.

**Comment by larsrh** [comment]
`v0.2.4` is queued.

**Comment by johnynek** [comment]
Thanks @larsrh !
