### ISSUE TITLE
More efficient pretty printer.

### ISSUE THREAD

**Issue by coltfred** [typelevel/paiges#35]
@johnynek I implemented this same pretty printer inside of optparse-applicative [here](https://github.com/bmjames/scala-optparse-applicative/pull/13). It unfortunately created [this](https://github.com/bmjames/scala-optparse-applicative/pull/16) issue.

I did resolve this, by implementing a [linear bounded](https://github.com/bmjames/scala-optparse-applicative/pull/16) implementation, which I plan to split out into its own library. Would you be interested in creating a common typeclass and hiding both of these behind it? 

Something like:

```
trait Doc[A] {
  def text(s: String): A
  def line: A
  def group(a: A): A
  def append(a1: A, a2: A): A
  def nest(i: Doc.Indent, a: A): A
  def nesting(f: Int => A): A
  def column(f: Int => A): A
}
```

We could define a bunch of other methods in terms of these basic ones.

The downside to the approach I'm suggesting is, it's ugly as sin. It's detailed [here](https://www.cs.kent.ac.uk/pubs/2009/2847/content.pdf) and even the haskell is awful. Add in Trampolining and bad type inference and it's bad.

I just wanted to open a dialog with you as having a single library for this would be great.

**Comment by johnynek** [comment]
Hey Colt.

I'm pretty sure the current implementation is `O(width)` in complexity. The code here is about 4 times slower than mkString in the benchmarks (and stack safe). I don't think we have any issues of exponential search.

It also has an Ordering implementation that is lawful, which is a nice side effect.

As for the type class, I don't think I want to add `column` and `nesting` if we can avoid it because each combinator greatly complicates the ordering, which I'd like to keep.

So, if we weakened your proposal to:
```scala
trait Doc[A] {
  def empty: A
  def text(s: String): A
  def line: A
  def lineBreak: A
  def group(a: A): A
  def append(a1: A, a2: A): A
  def nest(i: Int, a: A): A
  def align(a: A): A
}
```
it could be fine. I don't know where this would live. Paiges-core is zero dependency, but some submodule could wrap this.

**Comment by johnynek** [comment]
actually looking at your port, which I didn't see before I started this, I don't think you need nesting or column either, but align seems like enough.

The current code has align, btw (and does not use a trampoline, yet is stack safe and super fast).

**Comment by coltfred** [comment]
@johnynek Your optimization on `fill` might have been what I was missing. The optparse uses lots of `softline` calls, which in turn causes Unions (and I wasn't being fully lazy in the 2nd argument)

The paper I linked is bounded in the length of the doc. I think yours is O(docLength * width), but I could be wrong about that. Even so, without the cost of trampolines, it'll be way faster in practice.

The only combinator that you need `column` for, is `width`:

```
  /**
   * Return a document that renders `d` beside the document obtained by running
   * `f` on the width of `d`.
   */
  def width(d: Doc, f: Int => Doc): Doc = 
        column(j => append(d, column(k => f(k - j))))
```

Which was used for `fillBreak`:
```
  /**
   * Insert a possible line break and new nesting level instead of not
   * adding any padding.
   */
  def fillBreak(p: Int, d: Doc): Doc =
    width(d, w => if (w > p) nest(p, linebreak) else spaces(p - w))
```

There is no way to make the implementation I linked above stack-safe (I don't think). Since you've made Wadler's version stack-safe I don't see a way that the co-routine version would ever be actually faster in practice.

**Comment by johnynek** [comment]
@coltfred I wanted to invite you to work on this project if you want to and have time. You've obviously put a lot of thought in.

I'm trying to see if we can get away with not adding fillBreak actually. It seems a bit like a corner case to me, since in practice you almost always know the length of the things you are putting in columns with fillBreak.

My motivation is that I would really like to keep the total ordering on Doc, which is useful for things like SortedSets or creating reproducible documents when we have sets. Each new combinator that requires a new AST node significantly complicates the ordering. I have not seen any haskell implementations that have orderings, so it's not trivial.

I wonder if we could see if we could use paiges in opt-parse-applicative. What do you think? Are you interested in joining forces in this project?

**Comment by coltfred** [comment]
@johnynek Sure, it makes a ton of sense to collaborate on this. I'm busy this week, but after that let's build the best pretty printer! :laughing:

**Comment by johnynek** [comment]
I checked out your PR, and it seems that `fillBreak(s, d)` is actually only used (as I hoped) to generate tables (basically `List[(Doc, Doc)] => Doc`) but also when the left side is a String, so if we have `tabulate(tab: List[(String, Doc)]): Doc` I think we can side-step the complexity of `width` and `column` and keep our Ordering.

I'll take a stab at this.

**Comment by coltfred** [comment]
Closing this issue, as even a tighter bound won't compete with the trampolining needed (not to mention the hideous code needed).
