### ISSUE TITLE
Cross compile for version 2.11.x

### ISSUE THREAD

**Issue by jozanek** [typelevel/paiges#468]
It would be nice if we could get binaries for older (still in use) scala version 2.11

**Comment by johnynek** [comment]
There really haven't been any bugs found or changes to this library in quite a while (I think since we were publishing the 2.11 version).

Is there some problem you want addressed? If so, please report a bug.

I would be willing to add a 2.11 build back if we had some motivation, but I think you should be fine to use the last version published for 2.11 (which I use at work myself).
